language: android
env:
  global:
    - ANDROID_TARGET=android-21
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - tools
    - platform-tools
    - build-tools-21.1.1
    - android-21
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew connectedCheck
before_install:
  - chmod +x gradlew
after_success:
  - bash <(curl -s https://codecov.io/bash)